model:
  type: "MFAFES"
  MFAFES:
    feature_extract:
      input_dim: 75
      hidden_dim: 160
      tok: 0.5
    feature_align:
      input_size: [960, 41, 119]
      embed_dim: ${feature_extract.hidden_dim}
      seq_len: 10
    fusion:
      embed_dim: ${feature_extract.hidden_dim}
      num_heads: 8
    attention_encoder:
      num_layers: 6
      d_model: ${feature_extract.hidden_dim} * 4
      num_heads: 8
      d_ff: 2048
      dropout: 0.1
      embed_dim: ${feature_extract.hidden_dim}
    classifier:
      nb_classes: 2
      embed_dim: ${feature_extract.hidden_dim} * ${feature_align.seq_len}

training:
  ex_name: "First Fire" 
  batch_size: 64
  epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.002
  optimizer: "adam"
  loss_function: "cross_entropy"
  dependent: False
  n_folds: 10

data:
  name: "Ruiwen"
  Ruiwen:
    data_path: "/data/Ruiwen/data_with_ICA.pkl"
    subject_lists: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 33, 34]
    modalities: ['eeg', 'eye', 'au']
    input_size: [960, 41, 119]
    num_workers: 4
    ch_nums: 31
    ex_nums: 48

logging:
  log_dir: "/mnt/nvme1/yihaoyuan/Raven/RavenEx/multimodal_emotion_recognition/logs"
  model_dir: "/mnt/nvme1/yihaoyuan/Raven/RavenEx/multimodal_emotion_recognition/outputs"
  save_best_only: True

device:
  gpu: True
  gpu_ids: [0]

seed: 42
num_classes: 2